creation_rules:
  - path_regex: .*.enc
    encrypted_regex: ^(data|stringData)$
#    gcp_kms: projects/arc-mahir-sandbox/locations/global/keyRings/sandbox-keychain 
    gcp_kms: projects/arc-mahir-sandbox/locations/global/keyRings/sandbox-keychain/cryptoKeys/key01 
