apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: grafana
  repo: https://grafana.github.io/helm-charts 
  releaseName: grafana
  version: 7.0.8
  valuesFile: values.yaml
