---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-prd
  namespace: argocd-non-prod
spec:
  project: platform-admin
  destination:
    server: https://34.31.116.147
    namespace: jenkins-prd
  source:
#    plugin:
#      name: kustomize-enable-helm
    repoURL: https://github.com/striver121/platform_admin.git
    targetRevision: HEAD
    path: platform_apps/jenkins/overlays/prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secretstore-driver
  namespace: argocd-non-prod
spec:
  project: platform-admin
  destination:
    server: https://34.31.116.147
    namespace: kube-system
  source:
    repoURL: https://github.com/striver121/platform_admin.git
    targetRevision: HEAD
    path: platform_apps/csi-secretstore-driver/overlays/prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd-non-prod
spec:
  project: platform-admin
  destination:
    server: https://34.31.116.147
    namespace: vault
  source:
    repoURL: https://github.com/striver121/platform_admin.git
    targetRevision: HEAD
    path: platform_apps/vault/overlays/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: sonarqube
#  namespace: argocd-non-prod
#spec:
#  project: platform-admin
#  destination:
#    server: https://34.31.116.147
#    namespace: sonarqube
#  source:
#    repoURL: https://github.com/striver121/platform_admin.git
#    targetRevision: HEAD
#    path: platform_apps/sonarqube/overlays/prd
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#    - Validate=true
#    - CreateNamespace=true
#    retry:
#      limit: 5
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: nexus
#  namespace: argocd-non-prod
#spec:
#  project: platform-admin
#  destination:
#    server: https://34.31.116.147
#    namespace: nexus
#  source:
#    repoURL: https://github.com/striver121/platform_admin.git
#    targetRevision: HEAD
#    path: platform_apps/nexus/overlays/prd
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#    - Validate=true
#    - CreateNamespace=true
#    retry:
#      limit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd-non-prod
spec:
  project: platform-admin
  destination:
    server: https://34.31.116.147
    namespace: goldilocks
  source:
    repoURL: https://github.com/striver121/platform_admin.git
    targetRevision: HEAD
    path: platform_apps/goldilocks/overlays/prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: vpa
#  namespace: argocd-non-prod
#spec:
#  project: platform-admin
#  destination:
#    server: https://34.31.116.147
#    namespace: vpa
#  source:
#    repoURL: https://github.com/striver121/platform_admin.git
#    targetRevision: HEAD
#    path: platform_apps/vpa/overlays/prd
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#    - Validate=true
#    - CreateNamespace=true
#    retry:
#      limit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd-non-prod
spec:
  project: platform-admin
  destination:
    server: https://34.31.116.147
    namespace: prometheus
  source:
    repoURL: https://github.com/striver121/platform_admin.git
    targetRevision: HEAD
    path: platform_apps/prometheus/overlays/prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd-non-prod
spec:
  project: platform-admin
  destination:
    server: https://34.31.116.147
    namespace: grafana
  source:
    repoURL: https://github.com/striver121/platform_admin.git
    targetRevision: HEAD
    path: platform_apps/grafana/overlays/prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
