---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp-dev
  namespace: argocd-non-prod
spec:
  project: platform-devs
  destination:
    server: https://34.31.116.147
    namespace: demoapp-dev
  source:
    repoURL: https://github.com/striver121/platform_devs.git
    targetRevision: HEAD
    path: demoapp/overlays/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp-prd
  namespace: argocd-non-prod
spec:
  project: default
  destination:
    server: https://34.31.116.147
    namespace: demoapp-prd
  source:
    repoURL: https://github.com/striver121/platform_devs.git
    targetRevision: HEAD
    path: demoapp/overlays/prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
