---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-admin
spec:
  sourceRepos:
  - 'https://github.com/striver121/platform_admin.git'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceBlacklist:
  - group: ''
    kind: ''
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  syncWindows:
  - kind: allow
    schedule: '10 * * * *'
    duration: 1h
    applications:
    - '*'
    namespaces:
    - '*'
    clusters:
    - '*'
    manualSync: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-devs
spec:
  sourceRepos:
  - 'https://github.com/striver121/platform_devs.git'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceBlacklist:
  - group: ''
    kind: ''
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  syncWindows:
  - kind: allow
    schedule: '10 * * * *'
    duration: 1h
    applications:
    - '*'
    namespaces:
    - '*'
    clusters:
    - '*'
    manualSync: true
