apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
spec:
  template:
    spec:
      volumes:
        - name: jenkins-keys
          secret:
            secretName: jenkins-secrets
            items:
            - key: master.key
              path: master.key
            - key: hudson.util.Secret
              path: hudson.util.Secret
        - name: jenkins-credentials
          secret:
            secretName: jenkins-credentials
#            secretName: mysecret
            items:
            - key: credentials.xml
              path: credentials.xml
      containers:
        - name: jenkins
          volumeMounts:
          - name: jenkins-keys
            mountPath: /var/jenkins_home/secrets
            readOnly: true
          - name: jenkins-credentials
            mountPath: /var/jenkins_home/credentials.xml
            subPath: credentials.xml
            readOnly: true
  
