apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: gcp-sa
files:
    - generators/sa_json
disableNameSuffixHash: true
---
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: argocd-child-bitbucket-privatekey
files:
    - generators/bitbucketsecret
disableNameSuffixHash: true
---
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: cluster-ca-inc-spl3
envs:
    - generators/clusters/cluster-ca-inc-spl3.env
disableNameSuffixHash: true
