apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-non-prod

resources:
  - ../../base
  - resources/argocd-cluster-role-binding.yaml
  - patches/argocd-projects.yaml
  - apps/admin_apps.yaml
  - apps/dev_apps.yaml

#generators:
#  - generators/generator.yaml

patchesStrategicMerge:
  - resources/argocd-repo-server-deploy.yaml
#  - resources/argocd-repo-server-gcloud-sa.yaml
  - resources/argocd-server-role-binding.yaml
  - resources/argocd-application-controller-binding.yaml
  - patches/argocd-rbac.yaml
#  - patches/argocd-ingress-custom.yaml

patchesJson6902:
- target:
    group: ""
    version: v1
    kind: ConfigMap
    name: argocd-cm
  patch: |-
    - op: add
      path: data/data
#      value: {"kustomize.buildOptions": "--enable-helm"}
      value: {"kustomize.buildOptions": "--enable-helm --enable-alpha-plugins"}
- target:
    group: "rbac.authorization.k8s.io"
    version: v1
    kind: ClusterRole
    name: argocd-application-controller
  patch: |-
    - op: replace
      path: /metadata/name
      value: argocd-non-prod-application-controller-default
- target:
    group: "rbac.authorization.k8s.io"
    version: v1
    kind: ClusterRoleBinding
    name: argocd-application-controller
  patch: |-
    - op: replace
      path: /metadata/name
      value: argocd-non-prod-application-controller-default
- target:
    group: "rbac.authorization.k8s.io"
    version: v1
    kind: ClusterRole
    name: argocd-server
  patch: |-
    - op: replace
      path: /metadata/name
      value: argocd-non-prod-server-default
- target:
    group: "rbac.authorization.k8s.io"
    version: v1
    kind: ClusterRoleBinding
    name: argocd-server
  patch: |-
    - op: replace
      path: /metadata/name
      value: argocd-non-prod-server-default
- target:
    group: "policy"
    version: v1beta1
    kind: PodSecurityPolicy
    name: pod-security-policy-argocd
  patch: |-
    - op: replace
      path: /metadata/name
      value: pod-security-policy-argocd-non-prod
      
images:
 - name: quay.io/argoproj/argocd:v2.8.1
   newName: docker.io/striver121/argocdcustom
   newTag: v0.4
# - name: docker.io/striver121/argocdcustom:latest
#   newName: docker.io/striver121/argocdcustom
#   newTag: latest
 
configurations:
  - config/config.yaml
 
configMapGenerator:
    - name: kustomize-wrapper-vars
      literals:
#        - HOST='ca.argocd-non-prod.gcp.example.com'
        - ENV0='non-prod'
generatorOptions:
 disableNameSuffixHash: true

vars:
#  - name: INGRESS_HOST
#    objref:
#      kind: ConfigMap
#      name: kustomize-wrapper-vars
#      apiVersion: v1
#    fieldref:
#      fieldpath: data.HOST
  - name: ENV
    objref:
      kind: ConfigMap
      name: kustomize-wrapper-vars
      apiVersion: v1
    fieldref:
      fieldpath: data.ENV0

#value: [{"name": "vault-init","image": "nginx","imagePullPolicy": "IfNotPresent","volumeMounts": [{"mountPath": "/secret","name": "vault-secret"}],"env": [{"name": "VAULT_ENTRY","valueFrom": {"fieldRef": {"apiVersion": "v1","fieldPath": "metadata.annotations['vault.k8s.corp.net/role']"}}}]}]
#value: {"name": "vault-secret","emptyDir": {"medium": "Memory"}}      
