---
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: jenkins-secrets
files:
    - generators/secrets/master.key.base64.enc
    - generators/secrets/hudson.util.Secret.base64.enc
disableNameSuffixHash: true
---
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: jenkins-credentials
files:
    - generators/secrets/credentials.xml.base64.enc
disableNameSuffixHash: true
