---
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: jenkins-secrets
files:
    - generators/secrets/master.key
    - generators/secrets/hudson.util.Secret
disableNameSuffixHash: true
---
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: jenkins-credentials
files:
    - generators/secrets/credentials.xml
disableNameSuffixHash: true
---
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: jenkinscredentialsfile
files:
    - generators/secrets/secret.credentials.xml
disableNameSuffixHash: true
