apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: prometheus-operator-crds
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: prometheus-operator-crds
  version: 8.0.1
