apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: goldilocks
  repo: https://charts.fairwinds.com/stable
  releaseName: goldilocks
  version: 8.0.0
#  valuesFile: values.yaml
