apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: vault
  repo: https://helm.releases.hashicorp.com
  releaseName: vault
  version: 0.24.0
#  valuesFile: values.yaml
  valuesInline:
    injector:
      enable: false
    csi:
      enable: false
  
#  server:
#    dev:
#    enable: true
#  injector:
#    enable: false
#  csi:
#    enable: false
