---
apiVersion: v1
kind: Secret
metadata:
  name: platform-admin
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  - name: Platform-Admin
    type: git
    url: https://github.com/striver121/platform_admin.git
  - name: Platform-Devs
    type: git
    url: https://github.com/striver121/platform_devs.git
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: platform-admin
#  labels:
#    argocd.argoproj.io/secret-type: repository
#stringData:
#  name: Platform-Admin
#  type: git
#  url: https://github.com/striver121/platform_admin.git
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: platform-devs
#  labels:
#    argocd.argoproj.io/secret-type: repository
#stringData:
#  name: Platform-Devs
#  type: git
#  url: https://github.com/striver121/platform_devs.git
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-store-csi-driver
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: CSI-Driver
  type: helm
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: Jenkins
  type: helm
  url: https://charts.jenkins.io
---
apiVersion: v1
kind: Secret
metadata:
  name: bitnami
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: Bitnami
  type: helm
  url: https://charts.bitnami.com/bitnami
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: Cloudnative
  type: helm
  url: https://cloudnativeapp.github.io/charts/curated/
