apiVersion: v1
kind: Secret
metadata:
  name: secrets-store-csi-driver
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: ihttps://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
