apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: open-telemetry
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  releaseName: opentelemetry-operator
  version: 0.44.0
#  valuesFile: values.yaml
  valuesInline:
    admissionWebhooks:
      certManager:
        enabled: false
    admissionWebhooks:
      autoGenerateCert:
        enabled: true
