apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: opentelemetry-operator
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  releaseName: opentelemetry-operator
  version: 0.44.2
  valuesFile: values.yaml
#  valuesInline:
#    admissionWebhooks:
#      certManager:
#        enabled: false
#    admissionWebhooks:
#      autoGenerateCert:
#        enabled: true
