---
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: jenkins-secrets
files:
    - generators/secrets/secret.key
disableNameSuffixHash: true
---
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: jenkins-credentials
files:
    - generators/secrets/credentials.xml
disableNameSuffixHash: true
