apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: sonarqube
  repo: https://charts.bitnami.com/bitnami
  releaseName: sonarqube
  version: 4.0.2
#  valuesFile: values.yaml
  valuesInline:
    service:
      type: ClusterIP
