---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-$(ENV)-applications
  namespace: argocd-$(ENV)
spec:
  project: project-$(ENV)
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: bitbucket.org:example/argocd-$(ENV)-applications
    targetRevision: master
    path: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
