apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: csi-secrets-store
  includeCRDs: ture
  repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  releaseName: csi-secrets-store
  version: 1.3.4
  valuesInline:
    linux:
      syncSecret.enabled: true
      enableSecretRotation: true
