apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault
#namesuffix: -dev

resources:
  - ../../base
      
patchesJson6902:
- target:
    group: "apps"
    version: v1
    kind: DaemonSet
    name: vault-csi-provider
  patch: |-
    - op: add
      path: /spec/template/spec/containers/1/command/-
      value: vault && vault version
