apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault
#namesuffix: -dev

resources:
  - ../../base
      
patchesJson6902:
- target:
    group: "apps"
    version: v1
    kind: StatefulSet
    name: vault
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: vault kv put secret/my-pass password="$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 20 | head -1)"
