apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - ../../base

generators:
  - generators/generator.yaml

patchesStrategicMerge:
#  - patches/cluster-role-bindings.yaml
#  - patches/opentelemetrycert.yaml
