varReference:
- path: spec/rules/http/paths/backend/serviceName
  kind: Ingress
- path: spec/rules/host[0]
  kind: Ingress
- path: tls/hosts
  kind: Ingress
- path: data/scopes
  kind: ConfigMap
- path: data/policy.csv
  kind: ConfigMap
- path: metadata/name
  kind: Application
- path: metadata/namespace
  kind: Application
- path: spec/project
  kind: Application
- path: spec/source/repoURL
  kind: Application
- path: metadata/name
  kind: AppProject
- path: metadata/name
  kind: ClusterRoleBinding
- path: roleRef/name
  kind: ClusterRoleBinding
- path: subjects/namespace
  kind: ClusterRoleBinding
- path: metadata/name
  kind: ClusterRole


